/**
 * generated by Xtext 2.26.0
 */
package org.zumi.xtext.gbasm.gbasm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>And Cp</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.zumi.xtext.gbasm.gbasm.AndCp#getAndCpLabelRef <em>And Cp Label Ref</em>}</li>
 * </ul>
 *
 * @see org.zumi.xtext.gbasm.gbasm.GbasmPackage#getAndCp()
 * @model
 * @generated
 */
public interface AndCp extends Instruction
{
  /**
   * Returns the value of the '<em><b>And Cp Label Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>And Cp Label Ref</em>' reference.
   * @see #setAndCpLabelRef(LabelOrConstant)
   * @see org.zumi.xtext.gbasm.gbasm.GbasmPackage#getAndCp_AndCpLabelRef()
   * @model
   * @generated
   */
  LabelOrConstant getAndCpLabelRef();

  /**
   * Sets the value of the '{@link org.zumi.xtext.gbasm.gbasm.AndCp#getAndCpLabelRef <em>And Cp Label Ref</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>And Cp Label Ref</em>' reference.
   * @see #getAndCpLabelRef()
   * @generated
   */
  void setAndCpLabelRef(LabelOrConstant value);

} // AndCp
