/**
 * generated by Xtext 2.26.0
 */
package org.zumi.xtext.gbasm.gbasm;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Asm</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.zumi.xtext.gbasm.gbasm.Asm#getLabels <em>Labels</em>}</li>
 * </ul>
 *
 * @see org.zumi.xtext.gbasm.gbasm.GbasmPackage#getAsm()
 * @model
 * @generated
 */
public interface Asm extends EObject
{
  /**
   * Returns the value of the '<em><b>Labels</b></em>' containment reference list.
   * The list contents are of type {@link org.zumi.xtext.gbasm.gbasm.LabelOrConstant}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Labels</em>' containment reference list.
   * @see org.zumi.xtext.gbasm.gbasm.GbasmPackage#getAsm_Labels()
   * @model containment="true"
   * @generated
   */
  EList<LabelOrConstant> getLabels();

} // Asm
