/**
 * generated by Xtext 2.26.0
 */
package org.zumi.xtext.gbasm.gbasm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bank Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.zumi.xtext.gbasm.gbasm.BankReference#getBankLabel <em>Bank Label</em>}</li>
 * </ul>
 *
 * @see org.zumi.xtext.gbasm.gbasm.GbasmPackage#getBankReference()
 * @model
 * @generated
 */
public interface BankReference extends Ld
{
  /**
   * Returns the value of the '<em><b>Bank Label</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bank Label</em>' reference.
   * @see #setBankLabel(LabelOrConstant)
   * @see org.zumi.xtext.gbasm.gbasm.GbasmPackage#getBankReference_BankLabel()
   * @model
   * @generated
   */
  LabelOrConstant getBankLabel();

  /**
   * Sets the value of the '{@link org.zumi.xtext.gbasm.gbasm.BankReference#getBankLabel <em>Bank Label</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bank Label</em>' reference.
   * @see #getBankLabel()
   * @generated
   */
  void setBankLabel(LabelOrConstant value);

} // BankReference
