/**
 * generated by Xtext 2.26.0
 */
package org.zumi.xtext.gbasm.gbasm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Call Or Jump</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.zumi.xtext.gbasm.gbasm.CallOrJump#getAbsLabel <em>Abs Label</em>}</li>
 *   <li>{@link org.zumi.xtext.gbasm.gbasm.CallOrJump#getLocLabel <em>Loc Label</em>}</li>
 * </ul>
 *
 * @see org.zumi.xtext.gbasm.gbasm.GbasmPackage#getCallOrJump()
 * @model
 * @generated
 */
public interface CallOrJump extends Instruction
{
  /**
   * Returns the value of the '<em><b>Abs Label</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Abs Label</em>' reference.
   * @see #setAbsLabel(LabelOrConstant)
   * @see org.zumi.xtext.gbasm.gbasm.GbasmPackage#getCallOrJump_AbsLabel()
   * @model
   * @generated
   */
  LabelOrConstant getAbsLabel();

  /**
   * Sets the value of the '{@link org.zumi.xtext.gbasm.gbasm.CallOrJump#getAbsLabel <em>Abs Label</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Abs Label</em>' reference.
   * @see #getAbsLabel()
   * @generated
   */
  void setAbsLabel(LabelOrConstant value);

  /**
   * Returns the value of the '<em><b>Loc Label</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Loc Label</em>' reference.
   * @see #setLocLabel(LocalLabel)
   * @see org.zumi.xtext.gbasm.gbasm.GbasmPackage#getCallOrJump_LocLabel()
   * @model
   * @generated
   */
  LocalLabel getLocLabel();

  /**
   * Sets the value of the '{@link org.zumi.xtext.gbasm.gbasm.CallOrJump#getLocLabel <em>Loc Label</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Loc Label</em>' reference.
   * @see #getLocLabel()
   * @generated
   */
  void setLocLabel(LocalLabel value);

} // CallOrJump
