/**
 * generated by Xtext 2.26.0
 */
package org.zumi.xtext.gbasm.gbasm;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.zumi.xtext.gbasm.gbasm.GbasmPackage
 * @generated
 */
public interface GbasmFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GbasmFactory eINSTANCE = org.zumi.xtext.gbasm.gbasm.impl.GbasmFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Asm</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Asm</em>'.
   * @generated
   */
  Asm createAsm();

  /**
   * Returns a new object of class '<em>Label Or Constant</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Label Or Constant</em>'.
   * @generated
   */
  LabelOrConstant createLabelOrConstant();

  /**
   * Returns a new object of class '<em>Statement</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Statement</em>'.
   * @generated
   */
  Statement createStatement();

  /**
   * Returns a new object of class '<em>Local Label</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Local Label</em>'.
   * @generated
   */
  LocalLabel createLocalLabel();

  /**
   * Returns a new object of class '<em>Instruction</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Instruction</em>'.
   * @generated
   */
  Instruction createInstruction();

  /**
   * Returns a new object of class '<em>Ld</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ld</em>'.
   * @generated
   */
  Ld createLd();

  /**
   * Returns a new object of class '<em>Label Reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Label Reference</em>'.
   * @generated
   */
  LabelReference createLabelReference();

  /**
   * Returns a new object of class '<em>Bank Reference</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bank Reference</em>'.
   * @generated
   */
  BankReference createBankReference();

  /**
   * Returns a new object of class '<em>And Cp</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>And Cp</em>'.
   * @generated
   */
  AndCp createAndCp();

  /**
   * Returns a new object of class '<em>Call Or Jump</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Call Or Jump</em>'.
   * @generated
   */
  CallOrJump createCallOrJump();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  GbasmPackage getGbasmPackage();

} //GbasmFactory
