/**
 * generated by Xtext 2.26.0
 */
package org.zumi.xtext.gbasm.gbasm;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.zumi.xtext.gbasm.gbasm.GbasmFactory
 * @model kind="package"
 * @generated
 */
public interface GbasmPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "gbasm";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.zumi.org/xtext/gbasm/Gbasm";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "gbasm";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GbasmPackage eINSTANCE = org.zumi.xtext.gbasm.gbasm.impl.GbasmPackageImpl.init();

  /**
   * The meta object id for the '{@link org.zumi.xtext.gbasm.gbasm.impl.AsmImpl <em>Asm</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.zumi.xtext.gbasm.gbasm.impl.AsmImpl
   * @see org.zumi.xtext.gbasm.gbasm.impl.GbasmPackageImpl#getAsm()
   * @generated
   */
  int ASM = 0;

  /**
   * The feature id for the '<em><b>Labels</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASM__LABELS = 0;

  /**
   * The number of structural features of the '<em>Asm</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.zumi.xtext.gbasm.gbasm.impl.LabelOrConstantImpl <em>Label Or Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.zumi.xtext.gbasm.gbasm.impl.LabelOrConstantImpl
   * @see org.zumi.xtext.gbasm.gbasm.impl.GbasmPackageImpl#getLabelOrConstant()
   * @generated
   */
  int LABEL_OR_CONSTANT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_OR_CONSTANT__NAME = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_OR_CONSTANT__STATEMENTS = 1;

  /**
   * The number of structural features of the '<em>Label Or Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_OR_CONSTANT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.zumi.xtext.gbasm.gbasm.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.zumi.xtext.gbasm.gbasm.impl.StatementImpl
   * @see org.zumi.xtext.gbasm.gbasm.impl.GbasmPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 2;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.zumi.xtext.gbasm.gbasm.impl.LocalLabelImpl <em>Local Label</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.zumi.xtext.gbasm.gbasm.impl.LocalLabelImpl
   * @see org.zumi.xtext.gbasm.gbasm.impl.GbasmPackageImpl#getLocalLabel()
   * @generated
   */
  int LOCAL_LABEL = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOCAL_LABEL__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Local Label</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOCAL_LABEL_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.zumi.xtext.gbasm.gbasm.impl.InstructionImpl <em>Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.zumi.xtext.gbasm.gbasm.impl.InstructionImpl
   * @see org.zumi.xtext.gbasm.gbasm.impl.GbasmPackageImpl#getInstruction()
   * @generated
   */
  int INSTRUCTION = 4;

  /**
   * The number of structural features of the '<em>Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.zumi.xtext.gbasm.gbasm.impl.LdImpl <em>Ld</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.zumi.xtext.gbasm.gbasm.impl.LdImpl
   * @see org.zumi.xtext.gbasm.gbasm.impl.GbasmPackageImpl#getLd()
   * @generated
   */
  int LD = 5;

  /**
   * The feature id for the '<em><b>Loc Label</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LD__LOC_LABEL = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Ld</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LD_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.zumi.xtext.gbasm.gbasm.impl.LabelReferenceImpl <em>Label Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.zumi.xtext.gbasm.gbasm.impl.LabelReferenceImpl
   * @see org.zumi.xtext.gbasm.gbasm.impl.GbasmPackageImpl#getLabelReference()
   * @generated
   */
  int LABEL_REFERENCE = 6;

  /**
   * The feature id for the '<em><b>Loc Label</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_REFERENCE__LOC_LABEL = LD__LOC_LABEL;

  /**
   * The feature id for the '<em><b>Ref Label</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_REFERENCE__REF_LABEL = LD_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Label Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABEL_REFERENCE_FEATURE_COUNT = LD_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.zumi.xtext.gbasm.gbasm.impl.BankReferenceImpl <em>Bank Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.zumi.xtext.gbasm.gbasm.impl.BankReferenceImpl
   * @see org.zumi.xtext.gbasm.gbasm.impl.GbasmPackageImpl#getBankReference()
   * @generated
   */
  int BANK_REFERENCE = 7;

  /**
   * The feature id for the '<em><b>Loc Label</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BANK_REFERENCE__LOC_LABEL = LD__LOC_LABEL;

  /**
   * The feature id for the '<em><b>Bank Label</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BANK_REFERENCE__BANK_LABEL = LD_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Bank Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BANK_REFERENCE_FEATURE_COUNT = LD_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.zumi.xtext.gbasm.gbasm.impl.AndCpImpl <em>And Cp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.zumi.xtext.gbasm.gbasm.impl.AndCpImpl
   * @see org.zumi.xtext.gbasm.gbasm.impl.GbasmPackageImpl#getAndCp()
   * @generated
   */
  int AND_CP = 8;

  /**
   * The feature id for the '<em><b>And Cp Label Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_CP__AND_CP_LABEL_REF = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>And Cp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_CP_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.zumi.xtext.gbasm.gbasm.impl.CallOrJumpImpl <em>Call Or Jump</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.zumi.xtext.gbasm.gbasm.impl.CallOrJumpImpl
   * @see org.zumi.xtext.gbasm.gbasm.impl.GbasmPackageImpl#getCallOrJump()
   * @generated
   */
  int CALL_OR_JUMP = 9;

  /**
   * The feature id for the '<em><b>Abs Label</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALL_OR_JUMP__ABS_LABEL = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Loc Label</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALL_OR_JUMP__LOC_LABEL = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Call Or Jump</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CALL_OR_JUMP_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;


  /**
   * Returns the meta object for class '{@link org.zumi.xtext.gbasm.gbasm.Asm <em>Asm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Asm</em>'.
   * @see org.zumi.xtext.gbasm.gbasm.Asm
   * @generated
   */
  EClass getAsm();

  /**
   * Returns the meta object for the containment reference list '{@link org.zumi.xtext.gbasm.gbasm.Asm#getLabels <em>Labels</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Labels</em>'.
   * @see org.zumi.xtext.gbasm.gbasm.Asm#getLabels()
   * @see #getAsm()
   * @generated
   */
  EReference getAsm_Labels();

  /**
   * Returns the meta object for class '{@link org.zumi.xtext.gbasm.gbasm.LabelOrConstant <em>Label Or Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Label Or Constant</em>'.
   * @see org.zumi.xtext.gbasm.gbasm.LabelOrConstant
   * @generated
   */
  EClass getLabelOrConstant();

  /**
   * Returns the meta object for the attribute '{@link org.zumi.xtext.gbasm.gbasm.LabelOrConstant#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.zumi.xtext.gbasm.gbasm.LabelOrConstant#getName()
   * @see #getLabelOrConstant()
   * @generated
   */
  EAttribute getLabelOrConstant_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.zumi.xtext.gbasm.gbasm.LabelOrConstant#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see org.zumi.xtext.gbasm.gbasm.LabelOrConstant#getStatements()
   * @see #getLabelOrConstant()
   * @generated
   */
  EReference getLabelOrConstant_Statements();

  /**
   * Returns the meta object for class '{@link org.zumi.xtext.gbasm.gbasm.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see org.zumi.xtext.gbasm.gbasm.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link org.zumi.xtext.gbasm.gbasm.LocalLabel <em>Local Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Local Label</em>'.
   * @see org.zumi.xtext.gbasm.gbasm.LocalLabel
   * @generated
   */
  EClass getLocalLabel();

  /**
   * Returns the meta object for the attribute '{@link org.zumi.xtext.gbasm.gbasm.LocalLabel#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.zumi.xtext.gbasm.gbasm.LocalLabel#getName()
   * @see #getLocalLabel()
   * @generated
   */
  EAttribute getLocalLabel_Name();

  /**
   * Returns the meta object for class '{@link org.zumi.xtext.gbasm.gbasm.Instruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruction</em>'.
   * @see org.zumi.xtext.gbasm.gbasm.Instruction
   * @generated
   */
  EClass getInstruction();

  /**
   * Returns the meta object for class '{@link org.zumi.xtext.gbasm.gbasm.Ld <em>Ld</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ld</em>'.
   * @see org.zumi.xtext.gbasm.gbasm.Ld
   * @generated
   */
  EClass getLd();

  /**
   * Returns the meta object for the reference '{@link org.zumi.xtext.gbasm.gbasm.Ld#getLocLabel <em>Loc Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Loc Label</em>'.
   * @see org.zumi.xtext.gbasm.gbasm.Ld#getLocLabel()
   * @see #getLd()
   * @generated
   */
  EReference getLd_LocLabel();

  /**
   * Returns the meta object for class '{@link org.zumi.xtext.gbasm.gbasm.LabelReference <em>Label Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Label Reference</em>'.
   * @see org.zumi.xtext.gbasm.gbasm.LabelReference
   * @generated
   */
  EClass getLabelReference();

  /**
   * Returns the meta object for the reference '{@link org.zumi.xtext.gbasm.gbasm.LabelReference#getRefLabel <em>Ref Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref Label</em>'.
   * @see org.zumi.xtext.gbasm.gbasm.LabelReference#getRefLabel()
   * @see #getLabelReference()
   * @generated
   */
  EReference getLabelReference_RefLabel();

  /**
   * Returns the meta object for class '{@link org.zumi.xtext.gbasm.gbasm.BankReference <em>Bank Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bank Reference</em>'.
   * @see org.zumi.xtext.gbasm.gbasm.BankReference
   * @generated
   */
  EClass getBankReference();

  /**
   * Returns the meta object for the reference '{@link org.zumi.xtext.gbasm.gbasm.BankReference#getBankLabel <em>Bank Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Bank Label</em>'.
   * @see org.zumi.xtext.gbasm.gbasm.BankReference#getBankLabel()
   * @see #getBankReference()
   * @generated
   */
  EReference getBankReference_BankLabel();

  /**
   * Returns the meta object for class '{@link org.zumi.xtext.gbasm.gbasm.AndCp <em>And Cp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And Cp</em>'.
   * @see org.zumi.xtext.gbasm.gbasm.AndCp
   * @generated
   */
  EClass getAndCp();

  /**
   * Returns the meta object for the reference '{@link org.zumi.xtext.gbasm.gbasm.AndCp#getAndCpLabelRef <em>And Cp Label Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>And Cp Label Ref</em>'.
   * @see org.zumi.xtext.gbasm.gbasm.AndCp#getAndCpLabelRef()
   * @see #getAndCp()
   * @generated
   */
  EReference getAndCp_AndCpLabelRef();

  /**
   * Returns the meta object for class '{@link org.zumi.xtext.gbasm.gbasm.CallOrJump <em>Call Or Jump</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Call Or Jump</em>'.
   * @see org.zumi.xtext.gbasm.gbasm.CallOrJump
   * @generated
   */
  EClass getCallOrJump();

  /**
   * Returns the meta object for the reference '{@link org.zumi.xtext.gbasm.gbasm.CallOrJump#getAbsLabel <em>Abs Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Abs Label</em>'.
   * @see org.zumi.xtext.gbasm.gbasm.CallOrJump#getAbsLabel()
   * @see #getCallOrJump()
   * @generated
   */
  EReference getCallOrJump_AbsLabel();

  /**
   * Returns the meta object for the reference '{@link org.zumi.xtext.gbasm.gbasm.CallOrJump#getLocLabel <em>Loc Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Loc Label</em>'.
   * @see org.zumi.xtext.gbasm.gbasm.CallOrJump#getLocLabel()
   * @see #getCallOrJump()
   * @generated
   */
  EReference getCallOrJump_LocLabel();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GbasmFactory getGbasmFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.zumi.xtext.gbasm.gbasm.impl.AsmImpl <em>Asm</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.zumi.xtext.gbasm.gbasm.impl.AsmImpl
     * @see org.zumi.xtext.gbasm.gbasm.impl.GbasmPackageImpl#getAsm()
     * @generated
     */
    EClass ASM = eINSTANCE.getAsm();

    /**
     * The meta object literal for the '<em><b>Labels</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASM__LABELS = eINSTANCE.getAsm_Labels();

    /**
     * The meta object literal for the '{@link org.zumi.xtext.gbasm.gbasm.impl.LabelOrConstantImpl <em>Label Or Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.zumi.xtext.gbasm.gbasm.impl.LabelOrConstantImpl
     * @see org.zumi.xtext.gbasm.gbasm.impl.GbasmPackageImpl#getLabelOrConstant()
     * @generated
     */
    EClass LABEL_OR_CONSTANT = eINSTANCE.getLabelOrConstant();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LABEL_OR_CONSTANT__NAME = eINSTANCE.getLabelOrConstant_Name();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LABEL_OR_CONSTANT__STATEMENTS = eINSTANCE.getLabelOrConstant_Statements();

    /**
     * The meta object literal for the '{@link org.zumi.xtext.gbasm.gbasm.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.zumi.xtext.gbasm.gbasm.impl.StatementImpl
     * @see org.zumi.xtext.gbasm.gbasm.impl.GbasmPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link org.zumi.xtext.gbasm.gbasm.impl.LocalLabelImpl <em>Local Label</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.zumi.xtext.gbasm.gbasm.impl.LocalLabelImpl
     * @see org.zumi.xtext.gbasm.gbasm.impl.GbasmPackageImpl#getLocalLabel()
     * @generated
     */
    EClass LOCAL_LABEL = eINSTANCE.getLocalLabel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOCAL_LABEL__NAME = eINSTANCE.getLocalLabel_Name();

    /**
     * The meta object literal for the '{@link org.zumi.xtext.gbasm.gbasm.impl.InstructionImpl <em>Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.zumi.xtext.gbasm.gbasm.impl.InstructionImpl
     * @see org.zumi.xtext.gbasm.gbasm.impl.GbasmPackageImpl#getInstruction()
     * @generated
     */
    EClass INSTRUCTION = eINSTANCE.getInstruction();

    /**
     * The meta object literal for the '{@link org.zumi.xtext.gbasm.gbasm.impl.LdImpl <em>Ld</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.zumi.xtext.gbasm.gbasm.impl.LdImpl
     * @see org.zumi.xtext.gbasm.gbasm.impl.GbasmPackageImpl#getLd()
     * @generated
     */
    EClass LD = eINSTANCE.getLd();

    /**
     * The meta object literal for the '<em><b>Loc Label</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LD__LOC_LABEL = eINSTANCE.getLd_LocLabel();

    /**
     * The meta object literal for the '{@link org.zumi.xtext.gbasm.gbasm.impl.LabelReferenceImpl <em>Label Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.zumi.xtext.gbasm.gbasm.impl.LabelReferenceImpl
     * @see org.zumi.xtext.gbasm.gbasm.impl.GbasmPackageImpl#getLabelReference()
     * @generated
     */
    EClass LABEL_REFERENCE = eINSTANCE.getLabelReference();

    /**
     * The meta object literal for the '<em><b>Ref Label</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LABEL_REFERENCE__REF_LABEL = eINSTANCE.getLabelReference_RefLabel();

    /**
     * The meta object literal for the '{@link org.zumi.xtext.gbasm.gbasm.impl.BankReferenceImpl <em>Bank Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.zumi.xtext.gbasm.gbasm.impl.BankReferenceImpl
     * @see org.zumi.xtext.gbasm.gbasm.impl.GbasmPackageImpl#getBankReference()
     * @generated
     */
    EClass BANK_REFERENCE = eINSTANCE.getBankReference();

    /**
     * The meta object literal for the '<em><b>Bank Label</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BANK_REFERENCE__BANK_LABEL = eINSTANCE.getBankReference_BankLabel();

    /**
     * The meta object literal for the '{@link org.zumi.xtext.gbasm.gbasm.impl.AndCpImpl <em>And Cp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.zumi.xtext.gbasm.gbasm.impl.AndCpImpl
     * @see org.zumi.xtext.gbasm.gbasm.impl.GbasmPackageImpl#getAndCp()
     * @generated
     */
    EClass AND_CP = eINSTANCE.getAndCp();

    /**
     * The meta object literal for the '<em><b>And Cp Label Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_CP__AND_CP_LABEL_REF = eINSTANCE.getAndCp_AndCpLabelRef();

    /**
     * The meta object literal for the '{@link org.zumi.xtext.gbasm.gbasm.impl.CallOrJumpImpl <em>Call Or Jump</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.zumi.xtext.gbasm.gbasm.impl.CallOrJumpImpl
     * @see org.zumi.xtext.gbasm.gbasm.impl.GbasmPackageImpl#getCallOrJump()
     * @generated
     */
    EClass CALL_OR_JUMP = eINSTANCE.getCallOrJump();

    /**
     * The meta object literal for the '<em><b>Abs Label</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CALL_OR_JUMP__ABS_LABEL = eINSTANCE.getCallOrJump_AbsLabel();

    /**
     * The meta object literal for the '<em><b>Loc Label</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CALL_OR_JUMP__LOC_LABEL = eINSTANCE.getCallOrJump_LocLabel();

  }

} //GbasmPackage
