/**
 * generated by Xtext 2.26.0
 */
package org.zumi.xtext.gbasm.gbasm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instruction</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.zumi.xtext.gbasm.gbasm.GbasmPackage#getInstruction()
 * @model
 * @generated
 */
public interface Instruction extends Statement
{
} // Instruction
