/**
 * generated by Xtext 2.26.0
 */
package org.zumi.xtext.gbasm.gbasm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Label Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.zumi.xtext.gbasm.gbasm.LabelReference#getRefLabel <em>Ref Label</em>}</li>
 * </ul>
 *
 * @see org.zumi.xtext.gbasm.gbasm.GbasmPackage#getLabelReference()
 * @model
 * @generated
 */
public interface LabelReference extends Ld
{
  /**
   * Returns the value of the '<em><b>Ref Label</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ref Label</em>' reference.
   * @see #setRefLabel(LabelOrConstant)
   * @see org.zumi.xtext.gbasm.gbasm.GbasmPackage#getLabelReference_RefLabel()
   * @model
   * @generated
   */
  LabelOrConstant getRefLabel();

  /**
   * Sets the value of the '{@link org.zumi.xtext.gbasm.gbasm.LabelReference#getRefLabel <em>Ref Label</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ref Label</em>' reference.
   * @see #getRefLabel()
   * @generated
   */
  void setRefLabel(LabelOrConstant value);

} // LabelReference
