/**
 * generated by Xtext 2.26.0
 */
package org.zumi.xtext.gbasm.gbasm;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Label Or Constant</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.zumi.xtext.gbasm.gbasm.LabelOrConstant#getName <em>Name</em>}</li>
 *   <li>{@link org.zumi.xtext.gbasm.gbasm.LabelOrConstant#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see org.zumi.xtext.gbasm.gbasm.GbasmPackage#getLabelOrConstant()
 * @model
 * @generated
 */
public interface LabelOrConstant extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.zumi.xtext.gbasm.gbasm.GbasmPackage#getLabelOrConstant_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.zumi.xtext.gbasm.gbasm.LabelOrConstant#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link org.zumi.xtext.gbasm.gbasm.Statement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see org.zumi.xtext.gbasm.gbasm.GbasmPackage#getLabelOrConstant_Statements()
   * @model containment="true"
   * @generated
   */
  EList<Statement> getStatements();

} // LabelOrConstant
