/**
 * generated by Xtext 2.26.0
 */
package org.zumi.xtext.gbasm.gbasm;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ld</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.zumi.xtext.gbasm.gbasm.Ld#getLocLabel <em>Loc Label</em>}</li>
 * </ul>
 *
 * @see org.zumi.xtext.gbasm.gbasm.GbasmPackage#getLd()
 * @model
 * @generated
 */
public interface Ld extends Instruction
{
  /**
   * Returns the value of the '<em><b>Loc Label</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Loc Label</em>' reference.
   * @see #setLocLabel(LocalLabel)
   * @see org.zumi.xtext.gbasm.gbasm.GbasmPackage#getLd_LocLabel()
   * @model
   * @generated
   */
  LocalLabel getLocLabel();

  /**
   * Sets the value of the '{@link org.zumi.xtext.gbasm.gbasm.Ld#getLocLabel <em>Loc Label</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Loc Label</em>' reference.
   * @see #getLocLabel()
   * @generated
   */
  void setLocLabel(LocalLabel value);

} // Ld
