/**
 * generated by Xtext 2.26.0
 */
package org.zumi.xtext.gbasm.gbasm;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.zumi.xtext.gbasm.gbasm.GbasmPackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject
{
} // Statement
