/*
 * generated by Xtext 2.26.0
 */
package org.zumi.xtext.gbasm.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.zumi.xtext.gbasm.GbasmRuntimeModule;
import org.zumi.xtext.gbasm.GbasmStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class GbasmIdeSetup extends GbasmStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new GbasmRuntimeModule(), new GbasmIdeModule()));
	}
	
}
