/*
 * generated by Xtext 2.26.0
 */
package org.zumi.xtext.gbasm.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGbasmScopeProvider extends DelegatingScopeProvider {
}
