/*
 * generated by Xtext 2.26.0
 */
package org.zumi.xtext.gbasm.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.zumi.xtext.gbasm.parser.antlr.internal.InternalGbasmParser;
import org.zumi.xtext.gbasm.services.GbasmGrammarAccess;

public class GbasmParser extends AbstractAntlrParser {

	@Inject
	private GbasmGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGbasmParser createParser(XtextTokenStream stream) {
		return new InternalGbasmParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Asm";
	}

	public GbasmGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GbasmGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
