/*
 * generated by Xtext 2.26.0
 */
package org.zumi.xtext.gbasm.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractGbasmValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.zumi.xtext.gbasm.gbasm.GbasmPackage.eINSTANCE);
		return result;
	}
}
