/**
 * generated by Xtext 2.26.0
 */
package org.zumi.xtext.gbasm.gbasm.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.zumi.xtext.gbasm.gbasm.CallOrJump;
import org.zumi.xtext.gbasm.gbasm.GbasmPackage;
import org.zumi.xtext.gbasm.gbasm.LabelOrConstant;
import org.zumi.xtext.gbasm.gbasm.LocalLabel;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Call Or Jump</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.zumi.xtext.gbasm.gbasm.impl.CallOrJumpImpl#getAbsLabel <em>Abs Label</em>}</li>
 *   <li>{@link org.zumi.xtext.gbasm.gbasm.impl.CallOrJumpImpl#getLocLabel <em>Loc Label</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CallOrJumpImpl extends InstructionImpl implements CallOrJump
{
  /**
   * The cached value of the '{@link #getAbsLabel() <em>Abs Label</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAbsLabel()
   * @generated
   * @ordered
   */
  protected LabelOrConstant absLabel;

  /**
   * The cached value of the '{@link #getLocLabel() <em>Loc Label</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocLabel()
   * @generated
   * @ordered
   */
  protected LocalLabel locLabel;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CallOrJumpImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GbasmPackage.Literals.CALL_OR_JUMP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LabelOrConstant getAbsLabel()
  {
    if (absLabel != null && absLabel.eIsProxy())
    {
      InternalEObject oldAbsLabel = (InternalEObject)absLabel;
      absLabel = (LabelOrConstant)eResolveProxy(oldAbsLabel);
      if (absLabel != oldAbsLabel)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, GbasmPackage.CALL_OR_JUMP__ABS_LABEL, oldAbsLabel, absLabel));
      }
    }
    return absLabel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LabelOrConstant basicGetAbsLabel()
  {
    return absLabel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAbsLabel(LabelOrConstant newAbsLabel)
  {
    LabelOrConstant oldAbsLabel = absLabel;
    absLabel = newAbsLabel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GbasmPackage.CALL_OR_JUMP__ABS_LABEL, oldAbsLabel, absLabel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LocalLabel getLocLabel()
  {
    if (locLabel != null && locLabel.eIsProxy())
    {
      InternalEObject oldLocLabel = (InternalEObject)locLabel;
      locLabel = (LocalLabel)eResolveProxy(oldLocLabel);
      if (locLabel != oldLocLabel)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, GbasmPackage.CALL_OR_JUMP__LOC_LABEL, oldLocLabel, locLabel));
      }
    }
    return locLabel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LocalLabel basicGetLocLabel()
  {
    return locLabel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLocLabel(LocalLabel newLocLabel)
  {
    LocalLabel oldLocLabel = locLabel;
    locLabel = newLocLabel;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GbasmPackage.CALL_OR_JUMP__LOC_LABEL, oldLocLabel, locLabel));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GbasmPackage.CALL_OR_JUMP__ABS_LABEL:
        if (resolve) return getAbsLabel();
        return basicGetAbsLabel();
      case GbasmPackage.CALL_OR_JUMP__LOC_LABEL:
        if (resolve) return getLocLabel();
        return basicGetLocLabel();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GbasmPackage.CALL_OR_JUMP__ABS_LABEL:
        setAbsLabel((LabelOrConstant)newValue);
        return;
      case GbasmPackage.CALL_OR_JUMP__LOC_LABEL:
        setLocLabel((LocalLabel)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GbasmPackage.CALL_OR_JUMP__ABS_LABEL:
        setAbsLabel((LabelOrConstant)null);
        return;
      case GbasmPackage.CALL_OR_JUMP__LOC_LABEL:
        setLocLabel((LocalLabel)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GbasmPackage.CALL_OR_JUMP__ABS_LABEL:
        return absLabel != null;
      case GbasmPackage.CALL_OR_JUMP__LOC_LABEL:
        return locLabel != null;
    }
    return super.eIsSet(featureID);
  }

} //CallOrJumpImpl
